### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by changcc5** [gdub/python-simpleldap#6]
[root@reports-hammer-local tests]# pip install simpleldap
Requirement already satisfied (use --upgrade to upgrade): simpleldap in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): python-ldap in /usr/local/lib/python2.7/site-packages (from simpleldap)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages/setuptools-1.4.2-py2.7.egg (from python-ldap->simpleldap)
Cleaning up...
[root@reports-hammer-local tests]# python tests.py 
Traceback (most recent call last):
  File "tests.py", line 7, in <module>
    import simpleldap
ImportError: No module named simpleldap

I'm not sure how to fix this. Help?

**Comment by gdub** [comment]
Perhaps an issue with a previous installation or PYTHONPATH setup?  You can try reinstalling:

```
$ pip uninstall simpleldap
$ pip install simpleldap
```

Installing in a fresh virtualenv, I cannot reproduce the issue you're seeing:

```
tests$ virtualenv myenv
New python executable in myenv/bin/python
Installing setuptools, pip...done.

tests$ source myenv/bin/activate
(myenv) tests$ pip install simpleldap
Downloading/unpacking simpleldap
  Downloading simpleldap-0.8.tar.gz
  Running setup.py (path:/home/gdub/code/python-simpleldap/tests/myenv/build/simpleldap/setup.py) egg_info for package simpleldap
...
Successfully installed simpleldap python-ldap
Cleaning up...

(myenv) tests$ python tests.py
...
----------------------------------------------------------------------
Ran 21 tests in 4.749s

OK
```

Please re-open if you are able to reproduce using a fresh install.
