### ISSUE TITLE
Connected successfully or not?

### ISSUE THREAD

**Issue by shacker** [gdub/python-simpleldap#8]
It's not clear to me whether this is a bug or I'm doing something wrong. I'm able to make a connection, but then any attempt to use that connection says I'm not connected:

```
with simpleldap.Connection('directory.example.com') as conn:
    is_valid = conn.authenticate('uid=myuser,dc=directory,dc=example,dc=com', 'password')
```

(with my own substitutions of course) I get :

```
>>> is_valid
True
```

but then:

`conn.search("(&(givenName=Joe))")`

returns

`ldap.LDAPError: LDAP connection invalid`

**Comment by shacker** [comment]
Could this possibly be related to the LDAP version (just thinking out loud)? If so, how can I specify the version with simpleldap?

**Comment by gdub** [comment]
@shacker, Are you performing the `search()` inside or outside the with statement block?  The connection closes when the with block exits, so you will not be able to perform further actions on that same `conn` instance once outside the with block.

**Comment by shacker** [comment]
Ah, shoot. I've since moved on to just using the standard python-ldap lib rather than simpleldap. I no longer have the simpledap code I was testing, but I believe you are correct - I was searching from outside the block, thinking that connection remained open. Ah well, thanks.
